name: Create Release Branch

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Git user info
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git config --global --add safe.directory '*'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Update CHANGELOG.md
        run: |
          standard_version_output=$(standard-version --dry-run)
          new_tag=$(echo "$standard_version_output" | grep 'tagging release' | awk '{print $NF}')
          changelog=$(echo "$standard_version_output" | sed -n '/^---$/,/^---$/p' | sed '1d;$d')
          echo -e "\n\n$changelog\n\n$(cat CHANGELOG.md)" > CHANGELOG.tmp
          awk '/^## \[/{count++} count < 4' CHANGELOG.tmp > CHANGELOG.md
          sed -i 's/^---$/ /' CHANGELOG.md    
          sed -i '/^-e.*/d' CHANGELOG.md
          echo "NEW_TAG=${new_tag}" >> $GITHUB_ENV

      - name: Create and push new release branch
        run: |
          git checkout -b release/${{ env.NEW_TAG }}
          git push origin release/${{ env.NEW_TAG }}

      - name: Update package.json
        run: |
          if [ -z "${{ env.NEW_TAG }}" ]; then
            echo "No new version detected. Skipping package.json update."
            exit 0
          fi
          new_version=$(echo "${{ env.NEW_TAG }}" | sed 's/^v//')
          jq --arg version "$new_version" '.version = $version' package.json > package.json.tmp
          mv package.json.tmp package.json
          git add package.json
          git commit -m "chore: update version to ${{ env.NEW_TAG }}"

      - name: Commit CHANGELOG.md
        run: |
          git add CHANGELOG.md
          git commit -m "release: ${{ env.NEW_TAG }}"
          git push origin release/${{ env.NEW_TAG }}

      - name: Open pull request to master
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: "Release ${{ env.NEW_TAG }}"
          body: |
            Hi!
            This PR is for a new release ${{ env.NEW_TAG }} to be merged with master.
          source_branch: release/${{ env.NEW_TAG }}
          target_branch: main
          label: release

      - name: Open pull request to dev
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: "Changelog ${{ env.NEW_TAG }}"
          body: |
            Hi!
            This PR is for updating changelog for release ${{ env.NEW_TAG }} to be merged with dev.
          source_branch: release/${{ env.NEW_TAG }}
          target_branch: dev
          label: release
