name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Conventional Changelog Action
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          owner: "hashem"
          ignorePreReleases: "true"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push new release branch
        run: |
          git checkout -b release/${{ steps.changelog.output.toTag }}
          git push origin release/${{ steps.changelog.output.toTag }}

      - name: Open pull request to master
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: release ${{ steps.changelog.output.toTag }}
          body: |
            Hi!
            This PR is for a new release ${{ steps.changelog.output.toTag }} to be merged with master.
          source_branch: release/${{ steps.changelog.output.toTag }}
          target_branch: master
          assignee: hashemuhammed
          reviewer: hashemuhammed
          label: release

      - name: Open pull request to dev
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: changelog ${{ steps.changelog.output.toTag }}
          body: |
            Hi!
            This PR is for updating the changelog for release ${{ steps.changelog.output.toTag }} to be merged with dev.
          source_branch: release/${{ steps.changelog.output.toTag }}
          target_branch: dev
          assignee: hashemuhammed 
          reviewer: hashemuhammed 
          label: release
