name: Create Release Branch

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-push: 'false'
          git-message: 'chore(release): {version}'  
          release-count: '10'

      - name: Push new release branch
        run: |
          git checkout -b release/${{ steps.changelog.outputs.tag }}
          git push origin release/${{ steps.changelog.outputs.tag }}

      - name: Open pull reqeust to master
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: release ${{ steps.changelog.outputs.tag }}
          body: |
            Hi!
            This PR for a new release ${{ steps.changelog.outputs.tag }} to be merged with master.
          source_branch: release/${{ steps.changelog.outputs.tag }}
          target_branch: master
          assignee: hashemuhammed
          reviewer: hashemuhammed
          label: release


      - name: Open pull reqeust to dev
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: changelog ${{ steps.changelog.outputs.tag }}
          body: |
            Hi!
            This PR for updating changelog for release ${{ steps.changelog.outputs.tag }} to be merged with dev.
          source_branch: release/${{ steps.changelog.outputs.tag }}
          target_branch: dev
          assignee: hashemuhammed 
          reviewer: hashemuhammed 
          label: release
           