name: Create Release Branch

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          

      - name: Conventional Changelog Action
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Push new release branch
        run: |
          git checkout -b release/${{ github.ref_name  }}
          git push origin release/${{ github.ref_name  }}

      - name: Open pull reqeust to master
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: release ${{ github.ref_name  }}
          body: |
            Hi!
            This PR for a new release ${{ github.ref_name  }} to be merged with master.
          source_branch: release/${{ github.ref_name  }}
          target_branch: master
          assignee: hashemuhammed
          reviewer: hashemuhammed
          label: release


      - name: Open pull reqeust to dev
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: changelog ${{ github.ref_name  }}
          body: |
            Hi!
            This PR for updating changelog for release ${{ github.ref_name  }} to be merged with dev.
          source_branch: release/${{ github.ref_name  }}
          target_branch: dev
          assignee: hashemuhammed 
          reviewer: hashemuhammed 
          label: release
           