name: Create Release Branch

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - name: Set Git user info
      #   run: |
      #     git config --global user.email "actions@github.com"
      #     git config --global user.name "GitHub Actions"
          
      - name: Install dependencies
        run: |
          npm install -g standard-version
 
      - name: Update CHANGELOG.md
        run: |
          standard_version_output=$(standard-version --dry-run)
          new_tag=$(echo "$standard_version_output" | grep 'tagging release' | awk '{print $NF}')
          changelog=$(echo "$standard_version_output" | sed -n '/^---$/,/^---$/p' | sed '1d;$d')

          echo -e "\n\n$changelog\n\n$(cat CHANGELOG.md)" > CHANGELOG.tmp
          mv CHANGELOG.tmp CHANGELOG.md
          
          echo "NEW_TAG=${new_tag}" >> $GITHUB_ENV

      # - name: Update package.json
      #   run: |
      #     if [ -z "${{ env.NEW_TAG }}" ]; then
      #       echo "No new version detected. Skipping package.json update."
      #       exit 0
      #     fi
      #     new_version=$(echo "${{ env.NEW_TAG }}" | sed 's/^v//')
      #     jq --arg version "$new_version" '.version = $version' package.json > package.json.tmp
      #     mv package.json.tmp package.json
      #     git add package.json
      #     git commit -m "chore: update version to ${{ env.NEW_TAG }}"
        # env:
        #   GITHUB_TOKEN: ${{ secrets.MY_PAT }}


      - name: Create and push new release branch
        run: |
          git checkout -b release/${{ env.NEW_TAG }}
          git push origin release/${{ env.NEW_TAG }}


      # - name: Commit CHANGELOG.md 
      #   run: |
      #     git add CHANGELOG.md
      #     git commit -m "docs: update CHANGELOG.md for Release ${{ env.NEW_TAG }} [skip ci]"
      #     git push origin release/${{ env.NEW_TAG }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.MY_PAT }}


      - name: Open pull request to master 
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.MY_PAT }}
          title: "Release ${{ env.NEW_TAG }}"
          body: |
            Hi!
            This PR is for a new release ${{ env.NEW_TAG }} to be merged with master.
          source_branch: release/${{ env.NEW_TAG }}
          target_branch: main
          assignee: hashemuhammed
          label: release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}

      - name: Open pull request to dev
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.MY_PAT }}
          title: "Changelog ${{ env.NEW_TAG }}"
          body: |
            Hi!
            This PR is for updating changelog for release ${{ env.NEW_TAG }} to be merged with dev.
          source_branch: release/${{ env.NEW_TAG }}
          target_branch: dev
          assignee: hashemuhammed 
          label: release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
