name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_version: ${{ github.event.inputs.release_version }}

      - name: Push new release branch
        run: |
          git checkout -b release/${{ github.event.inputs.release_version }}
          git push origin release/${{ github.event.inputs.release_version }}

      - name: Open pull request to master
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: release ${{ github.event.inputs.release_version }}
          body: |
            Hi!
            This PR is for a new release ${{ github.event.inputs.release_version }} to be merged with master.
          source_branch: release/${{ github.event.inputs.release_version }}
          target_branch: master
          assignee: hashemuhammed
          reviewer: hashemuhammed
          label: release

      - name: Open pull request to dev
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: changelog ${{ github.event.inputs.release_version }}
          body: |
            Hi!
            This PR is for updating the changelog for release ${{ github.event.inputs.release_version }} to be merged with dev.
          source_branch: release/${{ github.event.inputs.release_version }}
          target_branch: dev
          assignee: hashemuhammed 
          reviewer: hashemuhammed 
          label: release
