name: Finalize Release
on:
  pull_request:
    types: 
      - closed
    branches:
      - main
      - dev 
jobs:
  finalize-release:
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        run: |
          echo "Event: ${{ toJson(github.event) }}"
