name: Finalize Release

on:
  push:
    branches:
      - main
      - dev

jobs:
  finalize-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Determine if branch is a release branch
        id: check_branch
        run: |
          echo "$branch_name"

          branch_name=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          
          if [[ "$branch_name" == release/* ]]; then
            echo "Branch is a release branch"
            echo "IS_RELEASE_BRANCH=true" >> $GITHUB_ENV
          else
            echo "Not a release branch"
            echo "IS_RELEASE_BRANCH=false" >> $GITHUB_ENV
          fi

      - name: Process Release Branch
        if: env.IS_RELEASE_BRANCH == 'true'
        run: |
          echo "Processing release branch..."
