name: Finalize Release
on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  finalize-release:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Echo branch name
        run: |
          echo "Branch name: ${{ github.event.pull_request.head.ref }}"
