name: Finalize Release

on:
  push:
    branches:
      - main

jobs:
  finalize-release:
    runs-on: ubuntu-latest
    env:
      - RELEASE_COMMIT_MESSAGE : "release/"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check for Release commit message and manage tags and branches
        id: check_and_manage
        run: |
          # Get commit messages
          commits=$(git log --pretty=format:"%s" HEAD^..HEAD)
          echo "Commit messages: $commits"

          # Check if the commit message contains the Release pattern
          if echo "$commits" | grep -q "$RELEASE_COMMIT_MESSAGE"; then
            echo "Release commit found with tag name: $tag_name"

            # Extract tag name from commit message
            tag_name=$(echo "$commits" | grep -oP '(?<=${RELEASE_COMMIT_MESSAGE})[^\s\[\]]+')
            branch_name="release/$tag_name"  

            echo "Extracted tag name: $tag_name"
            echo "Extracted branch name: $branch_name"

            # Create and push the new tag
            git tag $tag_name
            git push origin $tag_name 
            echo "Created and pushed new tag $tag_name"
          else
            echo "No Release commit found"
          fi


